version: '3'
services: 
    mysql-legacy:
        image: mysql:5.7
        ports:
            - "3309:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: test
        volumes:
            - "./data/mysql:/var/lib/mysql:rw"
            - "./conf/mysql.cnf:/etc/mysql/my.cnf"