version: "3"
services:
  # redis:
  #   image: redis:3.2
  #   hostname: redis
  #   volumes:
  #     - ./data/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
  #     - ./data/redis/data:/data # 持久化存储redis aof数据
  #   command: redis-server /usr/local/etc/redis/redis.conf # 使用配置文件启动redis
  #   ports:
  #     - 6379:6379
  # mysql-legacy:
  #   image: mysql:5.7
  #   ports:
  #     - "3309:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_DATABASE: test
  #   volumes:
  #     - "./data/mysql:/var/lib/mysql:rw"
  #     - "./data/mysql/conf/mysql.cnf:/etc/mysql/my.cnf"
  # neo4j:
  #     image: neo4j:4.1.1
  #     volumes:
  #     - ./data/neo4j/conf:/var/lib/neo4j/conf
  #     - ./data/neo4j/import:/var/lib/neo4j/import
  #     # - ./plugins:/plugins
  #     - ./data/neo4j:/data
  #     - ./data/neo4j/logs:/var/lib/neo4j/logs
  #     # restart: always
  #     ports:
  #     - 7474:7474
  #     - 7687:7687
  #     environment:
  #     - NEO4J_dbms_memory_heap_maxSize=4G
  #     - NEO4J_AUTH=neo4j/123456 #修改默认用户密码
  mongo:
    build: ./data/mongo/
    # restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/setup:/docker-entrypoint-initdb.d/
      - ./data/mongo/db:/data/db/ # 将容器中数据持久化到本地
      - ./data/mongo/configdb/:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: QWEASD123
  mongo-express: # web可视化界面
    depends_on:
      - mongo
    image: mongo-express:latest
    # restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: QWEASD123
